export const kgBasicsBlueprint = {
  introduction: [
    { slug: 'welcome', title: 'Welcome', order: 0, type: 'text', isLocked: false },
    { slug: 'whatYoullLearn', title: 'What You Will Learn', order: 1, type: 'text', isLocked: false },
    { slug: 'challengeAtScania', title: 'The Challenge at Scania', order: 2, type: 'text', isLocked: false },
    { slug: 'introQuiz', title: 'Quiz', order: 3, type: 'quiz', isLocked: false },
    { slug: 'bridgeToRdf', title: 'From Ideas to Structured Data', order: 4, type: 'text', isLocked: false },
  ],
  rdf: [
    { slug: 'rdfIntro', title: 'Introduction to RDF', order: 0, type: 'text', isLocked: false },
    { slug: 'anatomyOfATriple', title: 'The Anatomy of a Triple', order: 1, type: 'text', isLocked: false },
    { slug: 'whyTriplesMatter', title: 'Why triples matter', order: 2, type: 'text', isLocked: false },
    { slug: 'exerciseBuildATriple', title: 'Exercise: Build a Triple', order: 3, type: 'exercise', isLocked: false },
    { slug: 'URIsAndLinkedData', title: 'URIs and Linked Data', order: 4, type: 'text', isLocked: false },
    { slug: 'fullURIsNamespacesAndPrefixes', title: 'Full URIs, Namespaces & Prefixes', order: 5, type: 'text', isLocked: false },
    { slug: 'introRDFQuiz', title: 'Quiz: RDF Basics', order: 6, type: 'quiz', isLocked: false },
    { slug: 'rdfRecap', title: 'RDF Recap', order: 7, type: 'text', isLocked: false },
  ],
  ontologies: [
    { slug: 'ontologiesIntro', title: 'Introduction to Ontologies', order: 0, type: 'text', isLocked: false },
    { slug: 'ontologiesBlueprint', title: 'The Blueprint of Knowledge', order: 1, type: 'text', isLocked: false },
    { slug: 'exerciseBuildOntologyStatement', title: 'Exercise: Build a Tiny Ontology', order: 2, type: 'exercise', isLocked: false },
    { slug: 'ontologyVsData', title: 'Ontology vs. Data', order: 3, type: 'text', isLocked: false },
    { slug: 'ontologyRealWorldAnalogy', title: 'Real-World Analogy', order: 4, type: 'text', isLocked: false },
    { slug: 'exerciseBuildTinyOntology', title: 'Exercise: Build a Tiny Ontology', order: 5, type: 'exercise', isLocked: false },
    { slug: 'introOntologyQuiz', title: 'Quiz: Ontologies', order: 6, type: 'quiz', isLocked: false },
    { slug: 'ontologyRecap', title: 'Ontologies Recap & What’s Next', order: 7, type: 'text', isLocked: false },
  ],
  knowledgeGraphs: [
    { slug: 'knowledgeGraphsIntro', title: 'What is a Knowledge Graph?', order: 0, type: 'text', isLocked: false },
    { slug: 'knowledgeGraphsWhereAreTheyUsed', title: 'Where are Knowledge Graphs used?', order: 1, type: 'text', isLocked: false },
    { slug: 'knowledgeGraphsWhyUseThem', title: 'Why use Knowledge Graphs?', order: 2, type: 'text', isLocked: false },
    { slug: 'knowledgeGraphsDisconnectedData', title: 'Knowledge Graphs & Disconnected Data', order: 3, type: 'text', isLocked: false },
    { slug: 'knowledgeGraphsUseOntologies', title: 'How Knowledge Graphs use Ontologies', order: 4, type: 'text', isLocked: false },
    { slug: 'introKnowledgeGraphsQuiz', title: 'Quiz: Knowledge Graphs', order: 5, type: 'quiz', isLocked: false },
    { slug: 'knowledgeGraphsRecap', title: 'Knowledge Graphs Recap & What’s Next', order: 6, type: 'text', isLocked: false },
  ],
  querying: [
    { slug: 'queryingIntro', title: 'What is Querying?', order: 0, type: 'text', isLocked: false },
    { slug: 'queryingPrepareFirstQuery', title: 'Your first SPARQL Query', order: 1, type: 'text', isLocked: false },
    { slug: 'queryingFilterQuery', title: 'Narrowing your SPARL Query', order: 2, type: 'text', isLocked: false },
    { slug: 'queryingDistinct', title: 'Cleaning up with DISTINCT', order: 3, type: 'text', isLocked: false },
    { slug: 'queryingFilter', title: 'Filtering your SPARQL Query', order: 4, type: 'text', isLocked: false },
    { slug: 'exerciseSortSPARQLQuery', title: 'Exercise: Correct the Query', order: 5, type: 'exercise', isLocked: false },
    { slug: 'introQueryingQuiz', title: 'Quiz: Querying', order: 6, type: 'quiz', isLocked: false },
    { slug: 'queryingRecap', title: 'Querying Summary', order: 7, type: 'text', isLocked: false },
  ],
};
